locale = "en"
label = "English"
weight = 1
title = "Piero's home page"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/r2d2_xs.png"
  description = "Pierdomenico Fiadino — Data leader with 16 years of experience across R&D and SaaS. PhD in Data Mining, Head of Data @ Moss."
  copyright = "©2026 All Rights Reserved"

[params.author]
  name = "Pierdomenico Fiadino, PhD"
  headline = "Senior Director, Head of Data @ Moss"
  bio = "data stuff since 2010"
  links = [
     { email = "mailto:p@fiadino.org" },
     { github = "https://github.com/pierdom" },
     { linkedin = "https://linkedin.com/in/fiadino" },
{ researchgate = "https://www.researchgate.net/profile/Pierdomenico_Fiadino" },
     { telegram = "https://t.me/pierdom" },
  ]
